{
 "title": "Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Events processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(event_total[1m])" }
   ]
  },
  {
   "title": "Indicators",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(hits_on_category[1m])" }
   ]
  },
  {
   "title": "Cassandra load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(cassandra_loaded[1m])" }
   ]
  },
  {
   "title": "ElasticSearch load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_succeeded_sum[1m])"
    },
    {
     "expr": "rate(elasticsearch_failed_sum[1m])"
    }
   ]
  },
  {
   "title": "Pulsar in",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pulsar_rate_in" }
   ]
  },
  {
   "title": "Pulsar out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pulsar_rate_out" }
   ]
  },
  {
   "title": "Event latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(event_processing_time_sum[1m])"
    }
   ]
  }
 ]
}